version: '3.5'

services:
  mysqldb:
    image: mariadb:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    restart: unless-stopped
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data/csv_files:/etc/mysql/csv_files
      - ./data/sql:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./app
    restart: unless-stopped
    working_dir: /var/www/warpshop
    env_file: ./.env
    volumes:
      - ./app:/var/www/warpshop
      - /usr/src/app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
volumes:
  db_data: